#!/usr/bin/env bash
# Displays a list of currently running processes.

# Display header
printf "%-9s\t%-9s\t%-9s\t%-9s\t%-9s\t%-9s\t%-9s\t%-9s\t%-9s\t%-9s\n" "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "START" "TIME" "COMMAND"

# Loop through all processes
while IFS= read -r line; do
	# Extract process information
	user=$(echo "$line" | awk '{print $1}')
	pid=$(echo "$line" | awk '{print $2}')
	cpu=$(echo "$line" | awk '{print $3}')
	mem=$(echo "$line" | awk '{print $4}')
	vsz=$(echo "$line" | awk '{print $5}')
	rss=$(echo "$line" | awk '{print $6}')
	tty=$(echo "$line" | awk '{print $7}')
	stat=$(echo "$line" | awk '{print $8}')
	start=$(echo "$line" | awk '{print $9}')
	time=$(echo "$line" | awk '{print $10}')
	command=$(echo "$line" | awk '{$1=$2=$3=$4=$5=$6=$7=$8=$9=$10=""; print $0}')

	# Display process info
	printf "%-9s\t%-9s\t%-9s\t%-9s\t%-9s\t%-9s\t%-9s\t%-9s\t%-9s\t%-9s\n" "$user" "$pid" "$cpu" "$mem" "$vsz" "$rss" "$tty" "$stat" "$start" "$time" "$command"
done < <(ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd --sort=-%cpu | head -n 51 | tail -n +2)
