#!/usr/bin/env bash
#Using a while loop to read each line of the /etc/passwd file

while IFS=: read -r username _ userid _ homedir _
do
	echo "Username: $username"
	echo "User ID: $userid"
	echo "Home directory: $homedir"
done < /etc/passwd
