#!/usr/bin/env bash
#Using a while loop to read each line of the /etc/passwd file

while IFS=: read -r username _ groupid _ user_info homedir shell
do
	passcode=$(echo "$user_info" | cut -d ',' -f 1)
	info=$(echo "$user_info" | cut -d ',' -f 5-)
	echo "The user $username is part of the group $groupid gang, lives in $homedir, and rides $shell."
	echo "User ID's place is protected by the passcode $passcode, more info about the user here: $info"
done < /etc/passwd
