#!/usr/bin/env bash
#Parses the Apache logs
#Displaying visitor IP along with HTTP status code from Apache log file

awk -F' ' '{print $1, $9}' /alx-system_engineering-devops/0x04-loops_conditions_and_parsing/apache-access.log
